import type { Metadata } from 'next';
import { DefaultLayout } from '@/components/layout/default-layout'; // Your main layout component
import './globals.css'; // Global styles for the entire app. THIS IS THE ONLY PLACE FOR GLOBAL CSS IMPORTS.
import { TRPCProvider } from '@/utils/trpc-provider'; // We'll create this for tRPC

export const metadata: Metadata = {
  title: 'My Awesome App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children, // This prop contains the content of the current route segment (page or nested layout)
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/*
          Providers should ideally wrap the entire application.
          If TRPCProvider is a client component, it wraps the server components here.
          The DefaultLayout could be either a server or client component.
        */}
        <TRPCProvider> {/* This replaces trpc.withTRPC(MyApp) */}
          <DefaultLayout> {/* Your default UI wrapper */}
            {children} {/* This is where your actual page content or nested layouts will render */}
          </DefaultLayout>
        </TRPCProvider>
      </body>
    </html>
  );
}
